package atmAC;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import atmAC.ATMAccount;
import atmAC.atmAcRepository;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/atm") // This means URL's start with /atm (after Application path)

public class atmMainController {
	@Autowired // This means to get the bean called atmAcRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private atmAcRepository atmAcRepository;
	private double amtBalCurr;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewATM (@RequestParam String acNum
			, @RequestParam String transType, @RequestParam String accAmt
			, @RequestParam String comments){
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		//String amtDeposit;
		
	    ATMAccount c = new ATMAccount();
	    c.setAccNum(acNum);
	    c.setTransType(transType);
		c.setAccAmount(accAmt);
		c.settxtComment(comments);
		atmAcRepository.save(c);
		
		return "Saved";
		
	}
	
	@GetMapping(path="/all") 
	public @ResponseBody Iterable<ATMAccount>getAllATM()
	
	{
		return atmAcRepository.findAll();
	}
}	